// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PsnLib.Entities.SearchEntities
{
    public class AvatarUrl
    {

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("avatarUrl")]
        public string UserAvatarUrl { get; set; }
    }

}
