// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PsnLib.Entities.SearchEntities
{
    public class MiddleNameMatch
    {

        [JsonProperty("fromIndex")]
        public int FromIndex { get; set; }

        [JsonProperty("toIndex")]
        public int ToIndex { get; set; }
    }

}
