// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PsnLib.Entities.SearchEntities
{
    public class PersonalDetail
    {

        [JsonProperty("firstName")]
        public string FirstName { get; set; }

        [JsonProperty("middleName")]
        public string MiddleName { get; set; }

        [JsonProperty("lastName")]
        public string LastName { get; set; }

        [JsonProperty("profilePictureUrls")]
        public ProfilePictureUrl[] ProfilePictureUrls { get; set; }

        [JsonProperty("firstNameMatch")]
        public FirstNameMatch FirstNameMatch { get; set; }

        [JsonProperty("middleNameMatch")]
        public MiddleNameMatch MiddleNameMatch { get; set; }

        [JsonProperty("lastNameMatch")]
        public LastNameMatch LastNameMatch { get; set; }
    }

}
