// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PsnLib.Entities.SearchEntities
{
    public class ProfilePictureUrl
    {

        [JsonProperty("size")]
        public string Size { get; set; }

        [JsonProperty("profilePictureUrl")]
        public string UserProfilePictureUrl { get; set; }
    }

}
