// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace PsnLib.Entities.SearchEntities
{
    public class SearchResult
    {

        [JsonProperty("personalDetail")]
        public PersonalDetail PersonalDetail { get; set; }

        [JsonProperty("onlineId")]
        public string OnlineId { get; set; }

        [JsonProperty("avatarUrls")]
        public AvatarUrl[] AvatarUrls { get; set; }
    }

}
